### PR TITLE
Improve PAPI compatability

### PR DESCRIPTION
**Pull request by Andre601**
The goal is to improve PlaceholderAPI support as I can see some potential to improve things.

Right now, the following changes have been made:

- Moved argument handling to PAPICache class
- Use the Cache's `get` functionality to get the value or compute it if not present.
- Added new `world-total_<world>` and `world-loaded_<world>` options which act the same as `server-total` and `server-loaded` but for a specific world.
- Added `count-loaded` to player option to only list shops the player owns and that are loaded
- Added missing `persist` method to prevent the expansion from unloading during `/papi reload`

I keep this as a draft for now so that we can first discuss any additional changes and ideas.

### CODE REVIEW

**Comment by Andre601** [comment]
Pushed some changes to the general placeholder pattern. I consider this a **breaking change** because of how the patterns have been renamed to make more sense:

- `%qs_server-total%` -> `%qs_shops-total%`
- `%qs_server-loaded%` -> `%qs_shops-loaded`
- `%qs_player_<uuid>_count%` -> `%qs_player_shops-total%`

Additionally, the following changes have been made to the other placeholders:

- Removed `%qs_world-total_<world>%` in favour of `%qs_shops-total_<world>%`
- Removed `%qs_world-loaded_<world>%` in favour of `%qs_shops-loaded_<world>%`
- `%qs_player_<...>%` placeholders now take an optional UUID as the last value and otherwise use the player provided by PAPI itself.
  - For example: `%qs_player_shops-total%` now also has `%qs_player_shops-total_<uuid>%`

I added a small utility method in the Util class that checks a String for null or emptiness.

**Comment by Andre601** [comment]
You btw can ignore Codacy and Codiga warns... They yell about missing `default` statements in the switches despite them being there, so I assume they are too stupid to recognize Java 17 code...

**Comment by Andre601** [comment]
I was btw considering renaming the `getIdentifier` from `qs` to `quickshop` to easier identify it and avoid possible conflicts in case a plugin or expansion would use `qs` for whatever reason...

**Comment by Ghost-chu** [comment]
> I was btw considering renaming the `getIdentifier` from `qs` to `quickshop` to easier identify it and avoid possible conflicts in case a plugin or expansion would use `qs` for whatever reason...

Maybe it would be a good idea to allow user customization it?

**Comment by Andre601** [comment]
> > I was btw considering renaming the `getIdentifier` from `qs` to `quickshop` to easier identify it and avoid possible conflicts in case a plugin or expansion would use `qs` for whatever reason...
> 
> Maybe it would be a good idea to allow user customization it?

Not really. The identifier shouldn't be changeable, especially since PAPI is collecting stats about used Placeholder expansions and this feature could artificially alter it.

**Comment by Andre601** [comment]
Would still like to have a bit of discussion here...
I want to know if the changes are good, bad, something in-between, ...

**Comment by Ghost-chu** [comment]
I personally have no new suggestions, but this pr is still in draft status

**Comment by Andre601** [comment]
Yes, I left it a draft because I wanted input on this.
But if it is fine, I'll mark it as ready.

**Comment by Ghost-chu** [comment]
It seems that the network connection between Github CI and CodeMC is down these days, and the build often times out when connecting to CodeMC to download dependencies.

**Pull request merged**
